### ISSUE TITLE
Change email configuration to use other than gmail

### ISSUE THREAD

**Issue by sergio-ocon** [sergio-ocon/lastablas#16]
Gmail does consider this application to send spam, and thus is rejecting it and no authorization tokens are sent.

Test and configure another mail system that  works.

**Comment by sergio-ocon** [comment]
Or fix gmail

**Comment by sergio-ocon** [comment]
Two-factor authentication seems to do the trick, closing this issue

**Comment by alexvkcr** [comment]
I was developing a new branch to add mailchimp, should that idea be abandoned?

**Comment by sergio-ocon** [comment]
Why don't you create a branch with it so we can retake it if there are problems in production?
Just document quite well how to configure it and we can keep the code in its own branch without merging

**Comment by alexvkcr** [comment]
I will upload the branch and add a file with some links where to look into!

**Comment by alexvkcr** [comment]
Shoul I open a PR or leave it in our Repository pending news?
