### ISSUE TITLE
Should Rubocop be included in original repository

### ISSUE THREAD

**Issue by alexvkcr** [sergio-ocon/lastablas#9]
I used Rubocop yesterday and I found it quite useful, and hope to be using it in the future.

Is it appropriate if we include a PR with the necessary changes in the Gemfile to enable it?
@sergio-ocon @katafira @delaluzparra

**Comment by sergio-ocon** [comment]
Great idea:
Include it in travis-ci.yaml as a separate test and it should be great, but you need to solve two things:
- It should not stop the PR to be merged, it should just show there is someting wrong.
- It should be clear that the result of this needs to be shown as text, so you can easily review it.

If you can solve both, it is a nice addition

**Comment by sergio-ocon** [comment]
Added rubocop as a separate test, that is not mandatory. I don't know how to make results appear in the travis.yml results
